dataset:
  root: ../data/new_data
  plant_glob: "*"
  rgb_pattern: "color_{image}_{view}.png"
  depth_pattern: "depth_{image}_{view}.png"
  expected_views_per_image: 3
  view_ids: [0, 1, 2]

camera:
  intrinsics:
    width: 1280
    height: 720
    fx: 652.0978393554688
    fy: 650.5780639648438
    cx: 645.9053955078125
    cy: 363.380859375

depth:
  unit: realsense_units
  scale_m_per_unit: 9.999999747378752e-05
  treat_65535_as_invalid: true
  range_filter:
    enabled: true
    min_m: 0.05
    max_m: 0.60

segmentation:
  model_path: ../models/best.pt
  device: cpu
  imgsz: 640
  conf: 0.15
  iou: 0.40
  max_det: 100
  min_mask_area_px: 20000
  classes: []

  border_relax_factor: 0.25
  fallback_enabled: true
  fallback_conf: 0.25
  fallback_imgsz: 640
  fallback_min_mask_area_px: 600

  postprocess:
    enabled: true
    keep_largest_cc: true
    morph_open: true
    morph_close: true
    kernel_size: 5
    open_iters: 1
    close_iters: 1
    fill_holes: true

features:
  downsample_step: 1
  min_points: 50
  log_features: true

selected:
  enabled: true
  instance_id: 1
  min_pixels: 50
  darken_factor: 0.3
  draw_bbox: true

poses:
  pose_file: null
  default_pose:
    t_xyz: [0.0, 0.0, 0.0]
    q_xyzw: [0.0, 0.0, 0.0, 1.0]

robot:
  model: Meca500
  ip: ""
  wrf_equals_brf: true

  trf_set_during_capture_mm_deg: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  euler_convention: RzRyRx_deg
  pose_negate_angles: false
  pose_negate_translation: false

  cam_axes_correction_R_trf_cam_row_major_3x3: [
    0.0, -1.0, 0.0,
    1.0,  0.0, 0.0,
    0.0,  0.0, 1.0
  ]
  camera_in_trf_translation_mm: [0.0, 0.0, 0.0]

  views:
    "0":
      key: "l"
      pose_wrf_mm_deg: [-185.153, -60.253, -248.061, -63.286, -55.563, -127.337]
    "1":
      key: "m"
      pose_wrf_mm_deg: [-144.867, 0.000, -283.586, 180.000, -90.000, 0.000]
    "2":
      key: "r"
      pose_wrf_mm_deg: [-192.338, 36.919, -243.173, 71.161, -50.263, 104.430]

outputs:
  out_root: outputs
  save_overlay: true
  save_label_vis: true
  save_depth_mask_preview: true

  raw_cloud:
    enabled: true
    export_frame: all
    save_once_per_view: true
    overwrite: true
    ply_ascii: true
    debug: true

  cluster:
    enabled: true
    export_dirname: clusters
    distance_threshold_m: 0.06
    max_clusters: 50
    ply_ascii: true
    export_fused_plant_cloud: true
    fused_filename: plant_fused.ply
    fused_voxel_size: 0.0
    fused_max_points: 0
    max_points_per_cluster: 200000
    flip_y: false

